[package]
name = "serde-value"
version = "0.2.1"
authors = ["arcnmx"]

description = "Serialization value trees"
documentation = "http://arcnmx.github.io/serde-value/serde_value/"
repository = "https://github.com/arcnmx/serde-value"
readme = "README.md"
keywords = ["serde"]
license = "MIT"

[dependencies]
serde = "^0.7.0"
ordered-float = "^0.2.0"
