[package]
name = "serde-value"
version = "0.6.0"
authors = ["arcnmx"]

description = "Serialization value trees"
documentation = "http://arcnmx.github.io/serde-value/serde_value/"
repository = "https://github.com/arcnmx/serde-value"
readme = "README.md"
keywords = ["serde"]
license = "MIT"

[dependencies]
serde = "^1.0.0"
ordered-float = "^1.0.1"

[dev-dependencies]
serde_derive = "^1.0.0"
